#****************************************************************************
#
# SPDX-License-Identifier: MIT-0
# Copyright(c) 2019-2020 Intel Corporation.
#
#****************************************************************************

# TCL File Generated by Component Editor 25.1
# Thu Apr 03 13:04:20 PDT 2025
# DO NOT MODIFY


# 
# config_timeout "config_timeout" v1.0
#  2025.04.03.13:04:20
# 
# 

# 
# request TCL package from ACDS 25.1
# 
package require -exact qsys 25.1


# 
# module config_timeout
# 
set_module_property DESCRIPTION ""
set_module_property NAME config_timeout
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME config_timeout
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL configuration_timeout_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file configuration_timeout.sv SYSTEM_VERILOG PATH configuration_timeout.sv
add_fileset_file configuration_timeout_top.sv SYSTEM_VERILOG PATH configuration_timeout_top.sv TOP_LEVEL_FILE
add_fileset_file csr_register.sv SYSTEM_VERILOG PATH csr_register.sv
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH multiplexer.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL configuration_timeout_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file configuration_timeout.sv SYSTEM_VERILOG PATH configuration_timeout.sv
add_fileset_file configuration_timeout_top.sv SYSTEM_VERILOG PATH configuration_timeout_top.sv
add_fileset_file csr_register.sv SYSTEM_VERILOG PATH csr_register.sv
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH multiplexer.sv


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 14
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 14
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
set_parameter_property ADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property ADDR_WIDTH EXPORT true
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
set_parameter_property DATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property DATA_WIDTH EXPORT true
add_parameter RESP_WIDTH INTEGER 2
set_parameter_property RESP_WIDTH DEFAULT_VALUE 2
set_parameter_property RESP_WIDTH DISPLAY_NAME RESP_WIDTH
set_parameter_property RESP_WIDTH UNITS None
set_parameter_property RESP_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RESP_WIDTH AFFECTS_GENERATION false
set_parameter_property RESP_WIDTH HDL_PARAMETER true
set_parameter_property RESP_WIDTH TRANSFORM_PARAMETER false
set_parameter_property RESP_WIDTH EXPORT true
add_parameter CSR_ADDR_WIDTH INTEGER 8
set_parameter_property CSR_ADDR_WIDTH DEFAULT_VALUE 8
set_parameter_property CSR_ADDR_WIDTH DISPLAY_NAME CSR_ADDR_WIDTH
set_parameter_property CSR_ADDR_WIDTH UNITS None
set_parameter_property CSR_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property CSR_ADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property CSR_ADDR_WIDTH EXPORT true
add_parameter CSR_DATA_WIDTH INTEGER 32
set_parameter_property CSR_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property CSR_DATA_WIDTH DISPLAY_NAME CSR_DATA_WIDTH
set_parameter_property CSR_DATA_WIDTH UNITS None
set_parameter_property CSR_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_DATA_WIDTH HDL_PARAMETER true
set_parameter_property CSR_DATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property CSR_DATA_WIDTH EXPORT true
add_parameter CSR_BYTE_ENABLE_WIDTH INTEGER 4
set_parameter_property CSR_BYTE_ENABLE_WIDTH DEFAULT_VALUE 4
set_parameter_property CSR_BYTE_ENABLE_WIDTH DISPLAY_NAME CSR_BYTE_ENABLE_WIDTH
set_parameter_property CSR_BYTE_ENABLE_WIDTH UNITS None
set_parameter_property CSR_BYTE_ENABLE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_BYTE_ENABLE_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_BYTE_ENABLE_WIDTH HDL_PARAMETER true
set_parameter_property CSR_BYTE_ENABLE_WIDTH TRANSFORM_PARAMETER false
set_parameter_property CSR_BYTE_ENABLE_WIDTH EXPORT true
add_parameter LTSSM_STATE_WIDTH INTEGER 6
set_parameter_property LTSSM_STATE_WIDTH DEFAULT_VALUE 6
set_parameter_property LTSSM_STATE_WIDTH DISPLAY_NAME LTSSM_STATE_WIDTH
set_parameter_property LTSSM_STATE_WIDTH UNITS None
set_parameter_property LTSSM_STATE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LTSSM_STATE_WIDTH AFFECTS_GENERATION false
set_parameter_property LTSSM_STATE_WIDTH HDL_PARAMETER true
set_parameter_property LTSSM_STATE_WIDTH TRANSFORM_PARAMETER false
set_parameter_property LTSSM_STATE_WIDTH EXPORT true
add_parameter AWID_WIDTH INTEGER 4
set_parameter_property AWID_WIDTH DEFAULT_VALUE 4
set_parameter_property AWID_WIDTH DISPLAY_NAME AWID_WIDTH
set_parameter_property AWID_WIDTH UNITS None
set_parameter_property AWID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWID_WIDTH AFFECTS_GENERATION false
set_parameter_property AWID_WIDTH HDL_PARAMETER true
set_parameter_property AWID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AWID_WIDTH EXPORT true
add_parameter AWADDR_WIDTH INTEGER 64
set_parameter_property AWADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property AWADDR_WIDTH DISPLAY_NAME AWADDR_WIDTH
set_parameter_property AWADDR_WIDTH UNITS None
set_parameter_property AWADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AWADDR_WIDTH HDL_PARAMETER true
set_parameter_property AWADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AWADDR_WIDTH EXPORT true
add_parameter AWUSER_WIDTH INTEGER 16
set_parameter_property AWUSER_WIDTH DEFAULT_VALUE 16
set_parameter_property AWUSER_WIDTH DISPLAY_NAME AWUSER_WIDTH
set_parameter_property AWUSER_WIDTH UNITS None
set_parameter_property AWUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWUSER_WIDTH AFFECTS_GENERATION false
set_parameter_property AWUSER_WIDTH HDL_PARAMETER true
set_parameter_property AWUSER_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AWUSER_WIDTH EXPORT true
add_parameter AWLEN_WIDTH INTEGER 8
set_parameter_property AWLEN_WIDTH DEFAULT_VALUE 8
set_parameter_property AWLEN_WIDTH DISPLAY_NAME AWLEN_WIDTH
set_parameter_property AWLEN_WIDTH UNITS None
set_parameter_property AWLEN_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWLEN_WIDTH AFFECTS_GENERATION false
set_parameter_property AWLEN_WIDTH HDL_PARAMETER true
set_parameter_property AWLEN_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AWLEN_WIDTH EXPORT true
add_parameter WDATA_WIDTH INTEGER 256
set_parameter_property WDATA_WIDTH DEFAULT_VALUE 256
set_parameter_property WDATA_WIDTH DISPLAY_NAME WDATA_WIDTH
set_parameter_property WDATA_WIDTH UNITS None
set_parameter_property WDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property WDATA_WIDTH HDL_PARAMETER true
set_parameter_property WDATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property WDATA_WIDTH EXPORT true
add_parameter BID_WIDTH INTEGER 4
set_parameter_property BID_WIDTH DEFAULT_VALUE 4
set_parameter_property BID_WIDTH DISPLAY_NAME BID_WIDTH
set_parameter_property BID_WIDTH UNITS None
set_parameter_property BID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BID_WIDTH AFFECTS_GENERATION false
set_parameter_property BID_WIDTH HDL_PARAMETER true
set_parameter_property BID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property BID_WIDTH EXPORT true
add_parameter ARID_WIDTH INTEGER 4
set_parameter_property ARID_WIDTH DEFAULT_VALUE 4
set_parameter_property ARID_WIDTH DISPLAY_NAME ARID_WIDTH
set_parameter_property ARID_WIDTH UNITS None
set_parameter_property ARID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARID_WIDTH AFFECTS_GENERATION false
set_parameter_property ARID_WIDTH HDL_PARAMETER true
set_parameter_property ARID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property ARID_WIDTH EXPORT true
add_parameter ARADDR_WIDTH INTEGER 64
set_parameter_property ARADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property ARADDR_WIDTH DISPLAY_NAME ARADDR_WIDTH
set_parameter_property ARADDR_WIDTH UNITS None
set_parameter_property ARADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ARADDR_WIDTH HDL_PARAMETER true
set_parameter_property ARADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property ARADDR_WIDTH EXPORT true
add_parameter ARUSER_WIDTH INTEGER 16
set_parameter_property ARUSER_WIDTH DEFAULT_VALUE 16
set_parameter_property ARUSER_WIDTH DISPLAY_NAME ARUSER_WIDTH
set_parameter_property ARUSER_WIDTH UNITS None
set_parameter_property ARUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARUSER_WIDTH AFFECTS_GENERATION false
set_parameter_property ARUSER_WIDTH HDL_PARAMETER true
set_parameter_property ARUSER_WIDTH TRANSFORM_PARAMETER false
set_parameter_property ARUSER_WIDTH EXPORT true
add_parameter ARLEN_WIDTH INTEGER 8
set_parameter_property ARLEN_WIDTH DEFAULT_VALUE 8
set_parameter_property ARLEN_WIDTH DISPLAY_NAME ARLEN_WIDTH
set_parameter_property ARLEN_WIDTH UNITS None
set_parameter_property ARLEN_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARLEN_WIDTH AFFECTS_GENERATION false
set_parameter_property ARLEN_WIDTH HDL_PARAMETER true
set_parameter_property ARLEN_WIDTH TRANSFORM_PARAMETER false
set_parameter_property ARLEN_WIDTH EXPORT true
add_parameter RID_WIDTH INTEGER 4
set_parameter_property RID_WIDTH DEFAULT_VALUE 4
set_parameter_property RID_WIDTH DISPLAY_NAME RID_WIDTH
set_parameter_property RID_WIDTH UNITS None
set_parameter_property RID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RID_WIDTH AFFECTS_GENERATION false
set_parameter_property RID_WIDTH HDL_PARAMETER true
set_parameter_property RID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property RID_WIDTH EXPORT true
add_parameter RDATA_WIDTH INTEGER 256
set_parameter_property RDATA_WIDTH DEFAULT_VALUE 256
set_parameter_property RDATA_WIDTH DISPLAY_NAME RDATA_WIDTH
set_parameter_property RDATA_WIDTH UNITS None
set_parameter_property RDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property RDATA_WIDTH HDL_PARAMETER true
set_parameter_property RDATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property RDATA_WIDTH EXPORT true
add_parameter H2F_BAS_OUTSTANDING_PKT INTEGER 32
set_parameter_property H2F_BAS_OUTSTANDING_PKT DEFAULT_VALUE 32
set_parameter_property H2F_BAS_OUTSTANDING_PKT DISPLAY_NAME H2F_BAS_OUTSTANDING_PKT
set_parameter_property H2F_BAS_OUTSTANDING_PKT UNITS None
set_parameter_property H2F_BAS_OUTSTANDING_PKT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property H2F_BAS_OUTSTANDING_PKT AFFECTS_GENERATION false
set_parameter_property H2F_BAS_OUTSTANDING_PKT HDL_PARAMETER true
set_parameter_property H2F_BAS_OUTSTANDING_PKT TRANSFORM_PARAMETER false
set_parameter_property H2F_BAS_OUTSTANDING_PKT EXPORT true


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressGroup 0
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clk_i
set_interface_property csr associatedReset rstn_i
set_interface_property csr bitsPerSymbol 8
set_interface_property csr bridgedAddressOffset ""
set_interface_property csr bridgesToMaster ""
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 1
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr minimumResponseLatency 1
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr transparentBridge false
set_interface_property csr waitrequestAllowance 0
set_interface_property csr writeWaitTime 0
set_interface_property csr dfhFeatureGuid 0
set_interface_property csr dfhGroupId 0
set_interface_property csr dfhParameterId ""
set_interface_property csr dfhParameterName ""
set_interface_property csr dfhParameterVersion ""
set_interface_property csr dfhParameterData ""
set_interface_property csr dfhParameterDataLength ""
set_interface_property csr dfhFeatureMajorVersion 0
set_interface_property csr dfhFeatureMinorVersion 0
set_interface_property csr dfhFeatureId 35
set_interface_property csr dfhFeatureType 3
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""
set_interface_property csr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr SV_INTERFACE_TYPE ""
set_interface_property csr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr csr_address_i address Input "((CSR_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port csr csr_read_i read Input 1
add_interface_port csr csr_write_i write Input 1
add_interface_port csr csr_writedata_i writedata Input "((CSR_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port csr csr_burstcount_i burstcount Input 1
add_interface_port csr csr_byteenable_i byteenable Input "(((CSR_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port csr csr_debugaccess_i debugaccess Input 1
add_interface_port csr csr_readdatavalid_o readdatavalid Output 1
add_interface_port csr csr_readdata_o readdata Output "((CSR_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port csr csr_waitrequest_o waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_i
# 
add_interface clk_i clock end
set_interface_property clk_i ENABLED true
set_interface_property clk_i EXPORT_OF ""
set_interface_property clk_i PORT_NAME_MAP ""
set_interface_property clk_i CMSIS_SVD_VARIABLES ""
set_interface_property clk_i SVD_ADDRESS_GROUP ""
set_interface_property clk_i IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk_i SV_INTERFACE_TYPE ""
set_interface_property clk_i SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk_i clk_i clk Input 1


# 
# connection point rstn_i
# 
add_interface rstn_i reset end
set_interface_property rstn_i associatedClock clk_i
set_interface_property rstn_i synchronousEdges DEASSERT
set_interface_property rstn_i ENABLED true
set_interface_property rstn_i EXPORT_OF ""
set_interface_property rstn_i PORT_NAME_MAP ""
set_interface_property rstn_i CMSIS_SVD_VARIABLES ""
set_interface_property rstn_i SVD_ADDRESS_GROUP ""
set_interface_property rstn_i IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rstn_i SV_INTERFACE_TYPE ""
set_interface_property rstn_i SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rstn_i rstn_i reset_n Input 1


# 
# connection point config_in
# 
add_interface config_in avalon end
set_interface_property config_in addressGroup 0
set_interface_property config_in addressUnits SYMBOLS
set_interface_property config_in associatedClock clk_i
set_interface_property config_in associatedReset rstn_i
set_interface_property config_in bitsPerSymbol 8
set_interface_property config_in bridgedAddressOffset ""
set_interface_property config_in bridgesToMaster ""
set_interface_property config_in burstOnBurstBoundariesOnly false
set_interface_property config_in burstcountUnits WORDS
set_interface_property config_in explicitAddressSpan 0
set_interface_property config_in holdTime 0
set_interface_property config_in linewrapBursts false
set_interface_property config_in maximumPendingReadTransactions 1
set_interface_property config_in maximumPendingWriteTransactions 1
set_interface_property config_in minimumResponseLatency 1
set_interface_property config_in readLatency 0
set_interface_property config_in readWaitTime 1
set_interface_property config_in setupTime 0
set_interface_property config_in timingUnits Cycles
set_interface_property config_in transparentBridge false
set_interface_property config_in waitrequestAllowance 0
set_interface_property config_in writeWaitTime 0
set_interface_property config_in dfhFeatureGuid 0
set_interface_property config_in dfhGroupId 0
set_interface_property config_in dfhParameterId ""
set_interface_property config_in dfhParameterName ""
set_interface_property config_in dfhParameterVersion ""
set_interface_property config_in dfhParameterData ""
set_interface_property config_in dfhParameterDataLength ""
set_interface_property config_in dfhFeatureMajorVersion 0
set_interface_property config_in dfhFeatureMinorVersion 0
set_interface_property config_in dfhFeatureId 35
set_interface_property config_in dfhFeatureType 3
set_interface_property config_in ENABLED true
set_interface_property config_in EXPORT_OF ""
set_interface_property config_in PORT_NAME_MAP ""
set_interface_property config_in CMSIS_SVD_VARIABLES ""
set_interface_property config_in SVD_ADDRESS_GROUP ""
set_interface_property config_in IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property config_in SV_INTERFACE_TYPE ""
set_interface_property config_in SV_INTERFACE_MODPORT_TYPE ""

add_interface_port config_in hps_address_i address Input "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port config_in hps_writedata_i writedata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_in hps_read_i read Input 1
add_interface_port config_in hps_write_i write Input 1
add_interface_port config_in hps_burstcount_i burstcount Input 1
add_interface_port config_in hps_byteenable_i byteenable Input "(((DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port config_in hps_waitrequest_o waitrequest Output 1
add_interface_port config_in hps_readdatavalid_o readdatavalid Output 1
add_interface_port config_in hps_writerespvalid_o writeresponsevalid Output 1
add_interface_port config_in hps_readdata_o readdata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_in hps_resp_o response Output "((RESP_WIDTH - 1)) - (0) + 1"
set_interface_assignment config_in embeddedsw.configuration.isFlash 0
set_interface_assignment config_in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment config_in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment config_in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point config_out
# 
add_interface config_out avalon start
set_interface_property config_out addressGroup 0
set_interface_property config_out addressUnits SYMBOLS
set_interface_property config_out associatedClock clk_i
set_interface_property config_out associatedReset rstn_i
set_interface_property config_out bitsPerSymbol 8
set_interface_property config_out burstOnBurstBoundariesOnly false
set_interface_property config_out burstcountUnits WORDS
set_interface_property config_out doStreamReads false
set_interface_property config_out doStreamWrites false
set_interface_property config_out holdTime 0
set_interface_property config_out linewrapBursts false
set_interface_property config_out maximumPendingReadTransactions 0
set_interface_property config_out maximumPendingWriteTransactions 0
set_interface_property config_out minimumResponseLatency 1
set_interface_property config_out readLatency 0
set_interface_property config_out readWaitTime 1
set_interface_property config_out setupTime 0
set_interface_property config_out timingUnits Cycles
set_interface_property config_out waitrequestAllowance 0
set_interface_property config_out waitrequestTimeout 1024
set_interface_property config_out writeWaitTime 0
set_interface_property config_out enableConcurrentSubordinateAccess 0
set_interface_property config_out optimizedReadsWithBE 0
set_interface_property config_out ENABLED true
set_interface_property config_out EXPORT_OF ""
set_interface_property config_out PORT_NAME_MAP ""
set_interface_property config_out CMSIS_SVD_VARIABLES ""
set_interface_property config_out SVD_ADDRESS_GROUP ""
set_interface_property config_out IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property config_out SV_INTERFACE_TYPE ""
set_interface_property config_out SV_INTERFACE_MODPORT_TYPE ""

add_interface_port config_out cs_waitrequest_i waitrequest Input 1
add_interface_port config_out cs_readdatavalid_i readdatavalid Input 1
add_interface_port config_out cs_writerespvalid_i writeresponsevalid Input 1
add_interface_port config_out cs_resp_i response Input "((RESP_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_readdata_i readdata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_address_o address Output "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_writedata_o writedata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_read_o read Output 1
add_interface_port config_out cs_write_o write Output 1
add_interface_port config_out cs_burstcount_o burstcount Output 1
add_interface_port config_out cs_byteenable_o byteenable Output "(((DATA_WIDTH / 8) - 1)) - (0) + 1"


# 
# connection point hip_status
# 
add_interface hip_status conduit end
set_interface_property hip_status associatedClock clk_i
set_interface_property hip_status associatedReset ""
set_interface_property hip_status ENABLED true
set_interface_property hip_status EXPORT_OF ""
set_interface_property hip_status PORT_NAME_MAP ""
set_interface_property hip_status CMSIS_SVD_VARIABLES ""
set_interface_property hip_status SVD_ADDRESS_GROUP ""
set_interface_property hip_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property hip_status SV_INTERFACE_TYPE ""
set_interface_property hip_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port hip_status hip_status_linkup link_up Input 1
add_interface_port hip_status hip_status_dl_up dl_up Input 1
add_interface_port hip_status hip_status_surprise_down_err suprise_down_err Input 1
add_interface_port hip_status hip_status_ltssm_state ltssm_state Input "((LTSSM_STATE_WIDTH - 1)) - (0) + 1"


# 
# connection point csr_soft_rst
# 
add_interface csr_soft_rst conduit end
set_interface_property csr_soft_rst associatedClock clk_i
set_interface_property csr_soft_rst associatedReset ""
set_interface_property csr_soft_rst ENABLED true
set_interface_property csr_soft_rst EXPORT_OF ""
set_interface_property csr_soft_rst PORT_NAME_MAP ""
set_interface_property csr_soft_rst CMSIS_SVD_VARIABLES ""
set_interface_property csr_soft_rst SVD_ADDRESS_GROUP ""
set_interface_property csr_soft_rst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr_soft_rst SV_INTERFACE_TYPE ""
set_interface_property csr_soft_rst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr_soft_rst csr_axi_st_rst csr_axi_st_rst Output 1
add_interface_port csr_soft_rst csr_axi_lite_rst csr_axi_lite_rst Output 1


# 
# connection point hps2cfgto
# 
add_interface hps2cfgto axi4 end
set_interface_property hps2cfgto associatedClock axi_mm_clk
set_interface_property hps2cfgto associatedReset axi_mm_rst
set_interface_property hps2cfgto wakeupSignals false
set_interface_property hps2cfgto uniqueIdSupport false
set_interface_property hps2cfgto poison false
set_interface_property hps2cfgto traceSignals false
set_interface_property hps2cfgto isTranslator false
set_interface_property hps2cfgto dataCheck false
set_interface_property hps2cfgto addressCheck false
set_interface_property hps2cfgto securityAttribute false
set_interface_property hps2cfgto userData false
set_interface_property hps2cfgto readAcceptanceCapability 1
set_interface_property hps2cfgto writeAcceptanceCapability 1
set_interface_property hps2cfgto combinedAcceptanceCapability 1
set_interface_property hps2cfgto readDataReorderingDepth 1
set_interface_property hps2cfgto bridgesToMaster ""
set_interface_property hps2cfgto dfhFeatureGuid 0
set_interface_property hps2cfgto dfhGroupId 0
set_interface_property hps2cfgto dfhParameterId ""
set_interface_property hps2cfgto dfhParameterName ""
set_interface_property hps2cfgto dfhParameterVersion ""
set_interface_property hps2cfgto dfhParameterData ""
set_interface_property hps2cfgto dfhParameterDataLength ""
set_interface_property hps2cfgto dfhFeatureMajorVersion 0
set_interface_property hps2cfgto dfhFeatureMinorVersion 0
set_interface_property hps2cfgto dfhFeatureId 35
set_interface_property hps2cfgto dfhFeatureType 3
set_interface_property hps2cfgto ENABLED true
set_interface_property hps2cfgto EXPORT_OF ""
set_interface_property hps2cfgto PORT_NAME_MAP ""
set_interface_property hps2cfgto CMSIS_SVD_VARIABLES ""
set_interface_property hps2cfgto SVD_ADDRESS_GROUP ""
set_interface_property hps2cfgto IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property hps2cfgto SV_INTERFACE_TYPE ""
set_interface_property hps2cfgto SV_INTERFACE_MODPORT_TYPE ""

add_interface_port hps2cfgto hps2cfgto_axi_mm_awvalid awvalid Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_awready awready Output 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_awid awid Input "((AWID_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_awaddr awaddr Input "((AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_awuser awuser Input "((AWUSER_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_awlen awlen Input "((AWLEN_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_awsize awsize Input 3
add_interface_port hps2cfgto hps2cfgto_axi_mm_awburst awburst Input 2
add_interface_port hps2cfgto hps2cfgto_axi_mm_awprot awprot Input 3
add_interface_port hps2cfgto hps2cfgto_axi_mm_awlock awlock Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_wvalid wvalid Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_wlast wlast Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_wready wready Output 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_wdata wdata Input "((WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_wstrb wstrb Input "(((WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_bvalid bvalid Output 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_bready bready Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_bid bid Output "((BID_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_bresp bresp Output 2
add_interface_port hps2cfgto hps2cfgto_axi_mm_arvalid arvalid Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_arready arready Output 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_arid arid Input "((ARID_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_araddr araddr Input "((ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_aruser aruser Input "((ARUSER_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_arlen arlen Input "((ARLEN_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_arsize arsize Input 3
add_interface_port hps2cfgto hps2cfgto_axi_mm_arburst arburst Input 2
add_interface_port hps2cfgto hps2cfgto_axi_mm_arprot arprot Input 3
add_interface_port hps2cfgto hps2cfgto_axi_mm_arlock arlock Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_rvalid rvalid Output 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_rlast rlast Output 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_rready rready Input 1
add_interface_port hps2cfgto hps2cfgto_axi_mm_rid rid Output "((RID_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_rdata rdata Output "((RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port hps2cfgto hps2cfgto_axi_mm_rresp rresp Output 2


# 
# connection point cfgto2bas
# 
add_interface cfgto2bas axi4 start
set_interface_property cfgto2bas associatedClock axi_mm_clk
set_interface_property cfgto2bas associatedReset axi_mm_rst
set_interface_property cfgto2bas wakeupSignals false
set_interface_property cfgto2bas uniqueIdSupport false
set_interface_property cfgto2bas poison false
set_interface_property cfgto2bas traceSignals false
set_interface_property cfgto2bas isTranslator false
set_interface_property cfgto2bas dataCheck false
set_interface_property cfgto2bas addressCheck false
set_interface_property cfgto2bas securityAttribute false
set_interface_property cfgto2bas userData false
set_interface_property cfgto2bas readIssuingCapability 1
set_interface_property cfgto2bas writeIssuingCapability 1
set_interface_property cfgto2bas combinedIssuingCapability 1
set_interface_property cfgto2bas enableConcurrentSubordinateAccess 0
set_interface_property cfgto2bas noRepeatedIdsBetweenSubordinates 0
set_interface_property cfgto2bas issuesINCRBursts true
set_interface_property cfgto2bas issuesWRAPBursts true
set_interface_property cfgto2bas issuesFIXEDBursts true
set_interface_property cfgto2bas ENABLED true
set_interface_property cfgto2bas EXPORT_OF ""
set_interface_property cfgto2bas PORT_NAME_MAP ""
set_interface_property cfgto2bas CMSIS_SVD_VARIABLES ""
set_interface_property cfgto2bas SVD_ADDRESS_GROUP ""
set_interface_property cfgto2bas IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property cfgto2bas SV_INTERFACE_TYPE ""
set_interface_property cfgto2bas SV_INTERFACE_MODPORT_TYPE ""

add_interface_port cfgto2bas cfgto2bas_axi_mm_awvalid awvalid Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_awready awready Input 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_awid awid Output "((AWID_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_awaddr awaddr Output "((AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_awuser awuser Output "((AWUSER_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_awlen awlen Output "((AWLEN_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_awsize awsize Output 3
add_interface_port cfgto2bas cfgto2bas_axi_mm_awburst awburst Output 2
add_interface_port cfgto2bas cfgto2bas_axi_mm_awprot awprot Output 3
add_interface_port cfgto2bas cfgto2bas_axi_mm_awlock awlock Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_wvalid wvalid Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_wlast wlast Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_wready wready Input 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_wdata wdata Output "((WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_wstrb wstrb Output "(((WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_bvalid bvalid Input 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_bready bready Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_bid bid Input "((BID_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_bresp bresp Input 2
add_interface_port cfgto2bas cfgto2bas_axi_mm_arvalid arvalid Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_arready arready Input 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_arid arid Output "((ARID_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_araddr araddr Output "((ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_aruser aruser Output "((ARUSER_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_arlen arlen Output "((ARLEN_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_arsize arsize Output 3
add_interface_port cfgto2bas cfgto2bas_axi_mm_arburst arburst Output 2
add_interface_port cfgto2bas cfgto2bas_axi_mm_arprot arprot Output 3
add_interface_port cfgto2bas cfgto2bas_axi_mm_arlock arlock Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_rvalid rvalid Input 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_rlast rlast Input 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_rready rready Output 1
add_interface_port cfgto2bas cfgto2bas_axi_mm_rid rid Input "((RID_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_rdata rdata Input "((RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port cfgto2bas cfgto2bas_axi_mm_rresp rresp Input 2


# 
# connection point axi_mm_rst
# 
add_interface axi_mm_rst reset end
set_interface_property axi_mm_rst associatedClock clk_i
set_interface_property axi_mm_rst synchronousEdges DEASSERT
set_interface_property axi_mm_rst ENABLED true
set_interface_property axi_mm_rst EXPORT_OF ""
set_interface_property axi_mm_rst PORT_NAME_MAP ""
set_interface_property axi_mm_rst CMSIS_SVD_VARIABLES ""
set_interface_property axi_mm_rst SVD_ADDRESS_GROUP ""
set_interface_property axi_mm_rst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi_mm_rst SV_INTERFACE_TYPE ""
set_interface_property axi_mm_rst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi_mm_rst axi_mm_rst reset Input 1


# 
# connection point axi_mm_clk
# 
add_interface axi_mm_clk clock end
set_interface_property axi_mm_clk ENABLED true
set_interface_property axi_mm_clk EXPORT_OF ""
set_interface_property axi_mm_clk PORT_NAME_MAP ""
set_interface_property axi_mm_clk CMSIS_SVD_VARIABLES ""
set_interface_property axi_mm_clk SVD_ADDRESS_GROUP ""
set_interface_property axi_mm_clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi_mm_clk SV_INTERFACE_TYPE ""
set_interface_property axi_mm_clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi_mm_clk axi_mm_clk clk Input 1

