
/**
 * Abstract:
 * sysrp_h2f_write128_random_seq is used by test to provide initiator
 * scenario information to the Master agent present in the System Env.
 * This class defines a sequence in which a AXI WRITE followed by a AXI READ
 * sequence is generated by assigning values to the transactions rather than
 * randomization, and then transmitted using `uvm_send.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */

`ifndef GUARD_AXI_MASTER_DIRECTED_SEQUENCE_SV
`define GUARD_AXI_MASTER_DIRECTED_SEQUENCE_SV

class sysrp_h2f_write128_random_seq extends svt_axi_master_base_sequence;
  svt_axi_master_transaction write_tran;
  rand bit [3:0] wr_mode;
  /** Address to be written */
  rand bit [31:0] addr;
  rand bit [7:0] burst_length;
  bit [127:0] random_value;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(sysrp_h2f_write128_random_seq)

  /** Class Constructor */
  function new(string name="sysrp_h2f_write128_random_seq");
    super.new(name);
  endfunction
  
  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < 1; i++) begin
     
      if(wr_mode==1) begin
      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         = addr;
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
      write_tran.burst_size   = 'h4;
      write_tran.burst_length = burst_length;
      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
         write_tran.data[i] = {$urandom(),$urandom(),$urandom(),$urandom()};
      end
      foreach(write_tran.wstrb[i]) begin
        write_tran.wstrb[i] = 16'hffff;
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=0;
      end

      `uvm_info(get_type_name(),$sformatf(" SCB:: Pkt received from AXI Lite slave ENV \n %s",write_tran.sprint()),UVM_LOW)
      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);

     `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

      end
      else if(wr_mode==0) begin

      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.port_cfg     = cfg;
      read_tran.xact_type    = svt_axi_transaction::READ;
      read_tran.addr         = addr;
      read_tran.burst_type   = svt_axi_transaction::INCR;
      read_tran.burst_size   = 'h4;
      read_tran.atomic_type  = svt_axi_transaction::NORMAL;
      read_tran.burst_length = burst_length;
      read_tran.rresp        = new[read_tran.burst_length];
      read_tran.data         = new[read_tran.burst_length];
      read_tran.rready_delay = new[read_tran.burst_length];
      read_tran.data_user    = new[read_tran.burst_length];
      foreach (read_tran.rready_delay[i]) begin
        read_tran.rready_delay[i]=0;
      end

      /** Send the read transaction */
     `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
    
     `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
      end
    end

   `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: sysrp_h2f_write128_random_seq

`endif // GUARD_AXI_MASTER_DIRECTED_SEQUENCE_SV
